kind: pipeline
type: docker
name: default

platform:
  os: linux
  arch: arm64

steps:
- name: build
  image: jonoh/sccache-rust
  commands:
  - cargo build
  environment:
    SCCACHE_WEBDAV_ENDPOINT: "http://192.168.0.14:9999"
    SCCACHE_WEBDAV_KEY_PREFIX: "/cache"
